// sidebarsAssignments.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Autogenerate dari struktur folder `assignments/`
  assignmentsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
